### ISSUE TITLE
Make the documentation page the home page

### ISSUE THREAD

**Issue by mmirman** [anarchy-ai/anarchy-ai.github.io#4]
https://anarchy-ai.github.io/docs/category/home should be the first page you get to.

**Comment by AryPathania** [comment]
Docusaurus documentation on how to do so: https://docusaurus.io/docs/advanced/routing

**Comment by gokuljs** [comment]
i will pick this up

**Comment by gokuljs** [comment]
Hey @mmirman  and @AryPathania I want to ensure that I fully understand the goal we're trying to achieve with the documentation site. Could you please clarify if the intention is to make "https://anarchy-ai.github.io/docs/category/home" the primary landing page for all visitors to "https://anarchy-ai.github.io/"? In other words, should there be a direct redirection from the root URL to this specific documentation page, or should this page simply be the first one in the documentation hierarchy?

**Comment by mmirman** [comment]
Sorry @gokuljs this is kinda a dead issue!  If you want to help on docs, ping @T3CH3Y in discord
